iai_donbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  ur5_shoulder_pan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur5_shoulder_pan_joint
    pid: {p: 1000.0, i: 100, d: 10.0}
  ur5_shoulder_lift_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur5_shoulder_lift_joint
    pid: {p: 1000.0, i: 100, d: 10.0}
  ur5_elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur5_elbow_joint
    pid: {p: 1000.0, i: 100, d: 10.0}
  ur5_wrist_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur5_wrist_1_joint
    pid: {p: 1000.0, i: 100, d: 10.0}
  ur5_wrist_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur5_wrist_2_joint
    pid: {p: 1000.0, i: 100, d: 10.0}
  ur5_wrist_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur5_wrist_3_joint
    pid: {p: 1000.0, i: 100, d: 1.0}
  gripper_base_gripper_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_base_gripper_left_joint
    pid: {p: 5000.0, i: 100, d: 1.0}
  gripper_base_gripper_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_base_gripper_right_joint
    pid: {p: 5000.0, i: 100, d: 1.0}

  # Trajectory Controllers 
  whole_body_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
    gains:
      ur5_shoulder_pan_joint: {p: 5000.0, i: 100.0, d: 10.0}
      ur5_shoulder_lift_joint: {p: 5000.0, i: 100.0, d: 10.0}
      ur5_elbow_joint: {p: 5000.0, i: 100.0, d: 10.0}
      ur5_wrist_1_joint: {p: 5000.0, i: 100.0, d: 1.0}
      ur5_wrist_2_joint: {p: 5000.0, i: 100.0, d: 1.0}
      ur5_wrist_3_joint: {p: 5000.0, i: 100.0, d: 1.0}