iai_donbot:
  # parameters for Gazebo ROS control plugin
  gazebo_ros_control/pid_gains:
    ur5_shoulder_pan_joint: {p: 1000.0, i: 100, d: 100.0}
    ur5_shoulder_lift_joint: {p: 1000.0, i: 100, d: 100.0}
    ur5_elbow_joint: {p: 1000.0, i: 100, d: 100.0}
    ur5_wrist_1_joint: {p: 1000.0, i: 100, d: 100.0}
    ur5_wrist_2_joint: {p: 1000.0, i: 100, d: 100.0}
    ur5_wrist_3_joint: {p: 1000.0, i: 100, d: 100.0}
    gripper_base_gripper_left_joint: {p: 1000.0, i: 100, d: 100.0}
    gripper_base_gripper_right_joint: {p: 1000.0, i: 100, d: 100.0}

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  # Trajectory Controllers 
  whole_body_controller:
    type: position_controllers/JointTrajectoryController
    joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      ur5_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      ur5_elbow_joint: {trajectory: 0.2, goal: 0.1}
      ur5_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      ur5_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      ur5_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 125
    action_monitor_rate: 10